# Generated by Django 5.2.1 on 2025-05-25 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='fecha_hora_vencimiento',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
