# Generated by Django 5.2.1 on 2025-07-01 23:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0003_task_fecha_hora_inicio_alter_task_descripcion_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_slot', models.CharField(max_length=20, verbose_name='Horario')),
                ('day', models.CharField(choices=[('Monday', 'Lunes'), ('Tuesday', 'Martes'), ('Wednesday', 'Miércoles'), ('Thursday', 'Jueves'), ('Friday', 'Viernes'), ('Saturday', 'Sábado')], max_length=10, verbose_name='Día')),
                ('activity_text', models.CharField(max_length=200, verbose_name='Descripción')),
                ('activity_type', models.CharField(choices=[('class', 'Clase'), ('study', 'Estudio'), ('workout', 'Ejercicio'), ('meal', 'Comida'), ('routine', 'Rutina'), ('commute', 'Transporte'), ('break', 'Descanso'), ('social', 'Social'), ('review', 'Repaso'), ('open', 'Abierto'), ('other', 'Otro')], max_length=20, verbose_name='Tipo')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Horario',
                'verbose_name_plural': 'Horarios',
                'unique_together': {('usuario', 'time_slot', 'day')},
            },
        ),
    ]
