# Generated by Django 5.2.1 on 2025-07-02 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0004_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='agregar_al_horario',
            field=models.BooleanField(default=False, verbose_name='Agregar al horario semanal'),
        ),
        migrations.AddField(
            model_name='task',
            name='dia_semana',
            field=models.CharField(blank=True, choices=[('Monday', 'Lunes'), ('Tuesday', 'Martes'), ('Wednesday', 'Miércoles'), ('Thursday', 'Jueves'), ('Friday', 'Viernes'), ('Saturday', 'Sábado')], max_length=10, null=True, verbose_name='Día de la semana'),
        ),
        migrations.AddField(
            model_name='task',
            name='duracion_minutos',
            field=models.IntegerField(default=60, verbose_name='Duración (minutos)'),
        ),
        migrations.AddField(
            model_name='task',
            name='hora_inicio',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora de inicio'),
        ),
    ]
