# Generated by Django 5.2.1 on 2025-07-02 00:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0005_task_agregar_al_horario_task_dia_semana_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='tarea_relacionada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tareas.task', verbose_name='Tarea relacionada'),
        ),
    ]
