# Generated by Django 5.2.1 on 2025-07-02 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0006_schedule_tarea_relacionada'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='fecha_hora_inicio',
        ),
        migrations.RemoveField(
            model_name='task',
            name='fecha_hora_vencimiento',
        ),
    ]
