# Generated by Django 5.2.1 on 2025-07-16 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0007_remove_task_fecha_hora_inicio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='agregar_al_horario',
        ),
        migrations.DeleteModel(
            name='Schedule',
        ),
    ]
