# Generated by Django 5.2.1 on 2025-07-19 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0009_task_recordatorio_enviado'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='scheduled_dia_semana',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='scheduled_hora_inicio',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('completada', 'Completada')], default='pendiente', max_length=20, verbose_name='Estado'),
        ),
    ]
