# Generated by Django 5.2.1 on 2025-07-21 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0012_alter_task_dia_semana_jsonfield'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='dia_semana',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='Días de la semana'),
        ),
    ]
